### ISSUE TITLE
consent-manager_keycloak_setup_1 issue.

### ISSUE THREAD

**Issue by PranavKapadne** [ProjectEKA/consent-manager#347]
consent-manager_keycloak_setup_1 exits automatically in container when I run **docker-compose -f docker-compose-backend.yml start** 

Error:-
**exit-code =1;
Problem with request: Get http://keycloak:8080: dial tcp 172.18.0.5:8080: connect: connection refused. Sleeping 1s**

**Comment by ganesanarun** [comment]
When did you try? is your keycloak image `jboss/keycloak:9.0.2`

**Comment by PranavKapadne** [comment]
Just took a pull and tried ,facing same issue. Also, Starting cm-db-setup    ... failed
Starting hiu-db-setup   ... failed.

**Comment by zohairshaikh72** [comment]
Same issue here +1

**Comment by zohairshaikh72** [comment]
After spending some time I managed to find something that helped moving ahead..
```
keyclock: User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
```

So commenting KEYCLOAK_USER and KEYCLOAK_PASSWORD from `docker-compose-backend.yml` solved this 🤔

**Comment by PranavKapadne** [comment]
Command used: **docker-compose -f docker-compose.yml up --build**

**Log for Reference:**

12-jdk-alpine: Pulling from library/openjdk
6c40cc604d8e: Pull complete
9716b977a99b: Pull complete
Digest: sha256:fecd532eaee349b4d9e329148e99de77ffaf803e66e184a0e4d6b946bb97ffa3
Status: Downloaded newer image for openjdk:12-jdk-alpine
 ---> 0c68e7c5b7a0
Step 2/5 : VOLUME /tmp
 ---> Running in 1ee85a6727de
Removing intermediate container 1ee85a6727de
 ---> 2d6ad62fee16
Step 3/5 : COPY build/libs/* app.jar
**ERROR: Service 'consent-manager' failed to build: COPY failed: no source files were specified**
