### ISSUE TITLE
docker-compose -f docker-compose.yml up --build  failed with error on Step 3

### ISSUE THREAD

**Issue by PranavKapadne** [ProjectEKA/consent-manager#352]
**Command used: docker-compose -f docker-compose.yml up --build**

**Log for Reference:**

Building consent-manager
Step 1/5 : FROM openjdk:12-jdk-alpine
12-jdk-alpine: Pulling from library/openjdk
6c40cc604d8e: Pull complete
9716b977a99b: Pull complete
Digest: sha256:fecd532eaee349b4d9e329148e99de77ffaf803e66e184a0e4d6b946bb97ffa3
Status: Downloaded newer image for openjdk:12-jdk-alpine
 ---> 0c68e7c5b7a0
Step 2/5 : VOLUME /tmp
 ---> Running in 1ee85a6727de
Removing intermediate container 1ee85a6727de
 ---> 2d6ad62fee16
Step 3/5 : COPY build/libs/* app.jar
**ERROR: Service 'consent-manager' failed to build: COPY failed: no source files were specified**

**Comment by leelanakka** [comment]
can you try this now? @PranavKapadne

**Comment by ganesanarun** [comment]
https://github.com/ProjectEKA/consent-manager/blob/master/docs/dev-setup.md you can follow this.
