### ISSUE TITLE
cm_rabbitmq.json missing in master branch

### ISSUE THREAD

**Issue by vikram-soul** [ProjectEKA/consent-manager#528]
Unable to create CM queues as cm_rabbitmq.json is missing in the master branch. It is referenced in the [rabbitmqDeploy.sh](https://github.com/ProjectEKA/infrastructure/blob/master/rabbitmqDeploy.sh).

As a workaround I was able to pick it up from the CM_633 branch. Any plans to merge it into master?

**Comment by leelanakka** [comment]
We are working on that and will update you soon

**Comment by mddubey** [comment]
@vikram-soul We have added it back. Please try again.

**Comment by vikram-soul** [comment]
All set. Thanks
